### ISSUE TITLE
Checklist for Second Assignment

### ISSUE THREAD

**Issue by felix91gr** [felix91gr/tiny-c_compiler#1]
- [x] 50% **Código de su compilador** (lexer+parser en un solo ejecutable)
- [x] 8% **Entrega de código fuente para generar el compilador.** Descripción léxica (3%) y descripción de la gramática (5%).
* [x] 2% **Instrucciones para compilar** (readme, make o algo equivalente)
* [x] 10% **Entregar al menos dos archivos de código fuente** en el lenguaje a compilar, que deben pasar sin errores.
* [x] 10% **Entregar al menos tres archivos de código fuente** en el lenguaje a compilar, que deben fallar con errores de distinto tipo.
* [x] 10% **Si no hay errores** en el código de su lenguaje, **el programa debe generar el AST** correspondiente. El **AST debe permitir ver** o al menos acceder a la información relevante de cada nodo **(tipo, lexema si corresponde, fila, columna)**, y la relación padre-hijo.Para esta parte podremos probar con programas generados por el profesor+ayudante, además de los que deben entregar.
* [x] 5% **Si hay errores** en el código de entrada, el programa **no necesita generar ningún árbol** (podría hacerlo, pero no es necesario), pero sí debe avanzar lo más que pueda en el procesamiento del código de manera de detectar la mayor cantidad posible de errores. Para esta parte podremos probar con programas generados por el profesor+ayudante, además de los que deben entregar.
* [x] 5% **Los mensajes de error deben** ser adecuados, ser explicativos, e indicar fila y columna donde lo detectaron.
* [x] 30% Documento **PDF con la descripción** de:
    * [x] 5% **Lenguaje a compilar y lista de características incluidas** (solo lista, sin justificación). Snippets de código solo si es necesario para la comprensión.
    * [x] 5% **Lista de tokens y un ejemplo de cada uno** (más ejemplos solo si lo necesitan)
    * [x] 10% **Gramática del lenguaje**. Debe incluir lista de producciones, y tipo de gramática.
    * [x] 10% **Decisiones importantes sobre la gramática** (resolución de ambigüedades o precedencias). Aquí deben incluir restricciones adicionales sobre la gramática que puedan haber surgido en esta etapa.
    * [ ] 20% <del>Presentación donde deben mostrar:</del>
        * [ ] 2% Recordatorio del lenguaje (menor a 1 min)
        * [ ] 2% Lista de tokens (ejemplos solo si lo necesitan) (menor a 1 min)
        * [ ] 4% Decisiones importantes sobre la gramática (menor a 4 min)
        * [ ] 10% Demo de un programa sin errores (5%), y un programa con un error (5%) (menor a 4 min)
        * [ ] 2% Enviar la presentación.
