### ISSUE TITLE
Checklist for Polish and 100% done-ness

### ISSUE THREAD

**Issue by felix91gr** [felix91gr/tiny-c_compiler#3]
This issue pinpoints what's missing before I can consider this to be done as an example project for Pest and possibly Inkwell.

- [ ] Document required pre-installation of LLVM bits so that Inkwell works
- [ ] Refactor compiler, so that parsing, AST enrichment, semantic analysis and compiling are done in clearly separated ways.
- [ ] Localize language specifications
- [ ] Make Clippy pass all its default checks

**Comment by felix91gr** [comment]
Dependencies install: I had to install...

- `gcc`
- `g++`
- `zlib1g-dev`
- `llvm7` (changed dependency to branch llvm7-0 for Inkwell)

**Comment by felix91gr** [comment]
Another item for the list: **make Clippy pass all the checks**. Just turned on Clippy and it's pretty amazing, it looks like it'll be a good learning experience :D
